### ISSUE TITLE
Adding an attachment to a mail does not work

### ISSUE THREAD

**Issue by phsc84** [the-djmaze/rainloop-webmail#3]
**RainLoop version, browser, OS:**
1.14.0-djmaze3, Chrome 84.0.4147.125 (64-Bit), Windows 10 Home 1903

**Expected behavior and actual behavior:**
In the window to compose a new mail, an attachment could be added via drag&drop in the original Rainloop 1.14.0. Unfortunately this does not work in the djmaze3 version anymore.
It is also not possible to add an attachment via the file selection button.
![image](https://user-images.githubusercontent.com/2138442/90339981-0f9ab480-dff5-11ea-88f7-b8efd1ac111b.png)

**Steps to reproduce the problem:**
Just try to add an attachment.

**Logs or screenshots:**
Unfortunately nothing happens. No error pops up. It just does not add the attachment.

**Comment by the-djmaze** [comment]
Yes, this is fixed in the re-release of djmaze3 tar.gz and zip.
@h3artbl33d already reported it to me.
The problem was my incorrect replacement of $.ajax to FormData.

https://github.com/the-djmaze/rainloop-webmail/commit/9f73377a88319673512eea8e34e1bdb726e0eb66
https://github.com/the-djmaze/rainloop-webmail/commit/6f49e9b80f88e0154895bc6975fb029d630bd8a6

**Comment by the-djmaze** [comment]
Yes, this is fixed in the re-release of djmaze3 tar.gz and zip.
@h3artbl33d already reported it to me.
The problem was my incorrect replacement of $.ajax to FormData.

https://github.com/the-djmaze/rainloop-webmail/commit/9f73377a88319673512eea8e34e1bdb726e0eb66
https://github.com/the-djmaze/rainloop-webmail/commit/6f49e9b80f88e0154895bc6975fb029d630bd8a6
